# Generated by Django 3.2.3 on 2021-05-31 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('author', '0001_initial'),
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.URLField(blank=True)),
                ('blurb', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
                ('author', models.ManyToManyField(blank=True, to='author.Author')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.shelf')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
        ),
    ]
